version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0

executors:
  docker-executor:
    docker:
      - image: cimg/openjdk:11.0
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
          
jobs:
  test:
    executor: docker-executor
    steps:
      - checkout
      - run: |
          ./gradlew test
      - codecov/upload:
          file: './build/reports/jacoco/test/jacocoTestReport.xml'
  
  build:
    executor: docker-executor
    steps:
      - checkout
      - run: |
          ./gradlew build

workflows:
  my-custom-workflow:
    jobs:
      - test
      - build