version: '3.1'

services:

  mysql:
    image: mysql:8
    restart: always
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go
      MYSQL_USER: go_local
      MYSQL_PASSWORD: gogogo123